#! /bin/sh
#
# http_to_influx    redirecting http port 80 to influxdb2 port 9999
#
# chkconfig: 345
# description: redirecting http port 80 to influxdb2 port 9999
# processname: port_redirect

# Source function library.
. /etc/init.d/functions

SOURCE_PORT=80
DEST_PORT=9999
TASK="/home/isnflow/bin/port_redirect"

case "$1" in
  start)
    $TASK start $SOURCE_PORT $DEST_PORT
    ;;
  stop)
    $TASK stop $SOURCE_PORT $DEST_PORT
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  status)
    $TASK status $SOURCE_PORT $DEST_PORT
    ;;
  *)
    echo "Usage: /etc/init.d/http_to_influx {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
